TietgenRegnskab/Models/Udgift.cs
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TietgenRegnskab.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Udgift
    {
        public Udgift()
        {
            this.Beboers = new HashSet<Beboer>();
        }
    
        public int ID { get; set; }
        public int Beboer_ID { get; set; }
        public decimal Beloeb { get; set; }
        public string Beskrivelse { get; set; }
        public System.DateTime Dato { get; set; }
    
        public virtual Beboer Beboer { get; set; }
        public virtual ICollection<Beboer> Beboers { get; set; }
    }
}

TietgenRegnskab/Controllers/UdgiftController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TietgenRegnskab.Models;


namespace TietgenRegnskab.Controllers
{
    public class UdgiftController : Controller
    {
        TE _db = new TE();
        //
        // GET: /Udgift/


        public ActionResult Index(string beboerString,string takerString)
        {
            var model = from u in _db.Udgifts
                        select u;
            if(!String.IsNullOrEmpty(beboerString))
            {
                model = model.Where(u => u.Beboer.Name.Contains(beboerString));
            }
            if (!String.IsNullOrEmpty(takerString))
            {
                model = model.Where(u => u.Beboers.Contains(_db.Beboers.FirstOrDefault(b => b.Name.Contains(takerString))));
            }
            return View(model);
        }

        //
        // GET: /Udgift/Details/5

        public ActionResult Details(int id)
        {
            var udgift = _db.Udgifts.SingleOrDefault(U=>U.ID==id);
            var beboers = _db.Beboers;
            var model = new UdgiftCreateData(udgift, beboers);
            return View(model);
        }

        //
        // GET: /Udgift/Create

        public ActionResult Create()
        {
            return View(new UdgiftCreateData(new Udgift(),_db.Beboers.Where(B=>B.Moved_out==null)));
        } 

        //
        // POST: /Udgift/Create

        [HttpPost]
        public ActionResult Create(UdgiftCreateData udgiftdata,FormCollection postedForm)
        {
            try
            {
                List<Beboer> beboereToAdd = new List<Beboer>();
                Udgift udgift = udgiftdata.Udgift;
                var beboere = _db.Beboers.Where(B => B.Moved_out == null);
                foreach (var beboer in beboere)
                {
                    if (postedForm[beboer.Name].ToString().Contains("true"))
                    {
                        udgift.Beboers.Add(beboer);
                    }
                    else if(udgift.Beboers.Contains(beboer))
                        udgift.Beboers.Remove(beboer);
                }

                _db.Udgifts.Add(udgift);
                _db.SaveChanges();

                return RedirectToAction("Index");

            }
            catch
            {
                return View();
            }
        }

        
        //
        // GET: /Udgift/Edit/5


        public ActionResult Edit(int id)
        {
            var udgift = _db.Udgifts.SingleOrDefault(U => U.ID == id);
            var model = new UdgiftCreateData(udgift, _db.Beboers.Where(B => B.Moved_out == null));
            return View(model);
        }

        //
        // POST: /Udgift/Edit/5

        [HttpPost]
        public ActionResult Edit(int id,UdgiftCreateData udgiftdata, FormCollection postedForm)
        {
            try
            {
                List<Beboer> beboereToAdd = new List<Beboer>();
                Udgift udgift = udgiftdata.Udgift;
                var beboere = _db.Beboers.Where(B => B.Moved_out == null);
                foreach (var beboer in beboere)
                {
                    if (postedForm[beboer.Name].ToString().Contains("true"))
                    {
                        udgift.Beboers.Add(beboer);
                    }
                    else if (udgift.Beboers.Contains(beboer))
                        udgift.Beboers.Remove(beboer);
                }

                _db.Udgifts.Remove(_db.Udgifts.First(u => u.ID == id));
                _db.Udgifts.Add(udgift);
                _db.SaveChanges();

                return RedirectToAction("Index");

            }
            catch
            {
                return View();
            }
        }

        //
        // GET: /Udgift/Delete/5
        [Authorize]
        public ActionResult Delete(int id)
        {
            Udgift udgift = _db.Udgifts.Single(U => U.ID == id);
            return View(udgift);
        }

        //
        // POST: /Udgift/Delete/5
        [Authorize]
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                Udgift udgift = _db.Udgifts.Single(U => U.ID == id);
                _db.Udgifts.Remove(udgift);
                _db.SaveChanges();
 
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

TietgenRegnskab/Views/Udgift/Create.cshtml
@model TietgenRegnskab.Models.UdgiftCreateData

@{
    ViewBag.Title = "Create";
}

<h2>Create expense</h2>


<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>

@using (Html.BeginForm()){
    @Html.ValidationSummary(true)    
    <fieldset>
        <legend>Expense</legend>

        <div class="editor-label">  
            @Html.LabelFor(model => model.Udgift.Beboer_ID)
        </div>
        <div class="editor-field">
            @Html.DropDownListFor(model =>model.Udgift.Beboer_ID,new SelectList(Model.BeboerChecklist.Keys,"ID","Name",Model.BeboerChecklist),"--Vælg Beboer--")
            @Html.ValidationMessageFor(model => model.Udgift.Beboer_ID)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Udgift.Beloeb)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Udgift.Beloeb)
            @Html.ValidationMessageFor(model => model.Udgift.Beloeb)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Udgift.Beskrivelse)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Udgift.Beskrivelse)
            @Html.ValidationMessageFor(model => model.Udgift.Beskrivelse)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Udgift.Dato)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Udgift.Dato)
            @Html.ValidationMessageFor(model => model.Udgift.Dato)
        </div>
        
        @foreach (var beboer in @Model.BeboerChecklist)
        {
            @Html.CheckBox(beboer.Key.Name, beboer.Value);
            @Html.Label(beboer.Key.Name);
            <br />
        }
        
        <p>
            <input type="submit" value="Create" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

TietgenRegnskab/Views/Udgift/Delete.cshtml
@model TietgenRegnskab.Models.Udgift

@{
    ViewBag.Title = "Delete expense";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<fieldset>
    <legend>Udgift</legend>

    <div class="display-label">Beboer_ID</div>
    <div class="display-field">
        @*@Html.DisplayFor(model => model.Beboer_ID)*@
        @string.Format("{0:C}", Html.DisplayFor(model => model.Beboer.Name))
    </div>

    <div class="display-label">Beloeb</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Beloeb)
    </div>

    <div class="display-label">Beskrivelse</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Beskrivelse)
    </div>

    <div class="display-label">Dato</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Dato)
    </div>
</fieldset>
@using (Html.BeginForm()) {
    <p>
        <input type="submit" value="Delete" /> |
        @Html.ActionLink("Back to List", "Index")
    </p>
}

TietgenRegnskab/Views/Udgift/Details.cshtml
@model TietgenRegnskab.Models.UdgiftCreateData

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<fieldset>
    <p>
    @Html.ActionLink("Edit", "Edit", new { id=@Model.Udgift.ID })||
    @Html.ActionLink("Back to List", "Index")
</p>
    <legend>Udgift og deltagere</legend>
    <table>
     <tr>
         <th>
             Dato
         </th>
         <th>
             Betalt af
         </th>
         <th>
             Beskrivelse
         </th>
         <th>
             Beløb
         </th>
     </tr>
    <tr>
        <td>
            @Model.Udgift.Dato
        </td>
        <td>
            @Model.Udgift.Beboer.Name
        </td>
        <td>
            @Model.Udgift.Beskrivelse
        </td>
        <td>
            @string.Format("{0:C}", Model.Udgift.Beloeb);
        </td>
    </tr>

 </table>



@foreach (var category in @Model.BeboerChecklist)
{
@Html.CheckBox(category.Key.Name, category.Value, new { disabled = true })
@Html.Label(category.Key.Name)
        <br />

}


</fieldset>

TietgenRegnskab/Views/Udgift/Edit.cshtml
@model TietgenRegnskab.Models.UdgiftCreateData

@{
    ViewBag.Title = "Edit";
}


@{ 
    Html.EnableClientValidation(false); 
    } 


<h2>Edit</h2>

<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)
 <fieldset>
        <legend>Expense</legend>

        <div class="editor-label">  
            @Html.LabelFor(model => model.Udgift.Beboer_ID)
        </div>
        <div class="editor-field">
            @Html.DropDownListFor(model =>model.Udgift.Beboer_ID,new SelectList(Model.BeboerChecklist.Keys,"ID","Name",Model.BeboerChecklist),"--Vælg Beboer--")
            @Html.ValidationMessageFor(model => model.Udgift.Beboer_ID)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Udgift.Beloeb)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Udgift.Beloeb)
            @Html.ValidationMessageFor(model => model.Udgift.Beloeb)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Udgift.Beskrivelse)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Udgift.Beskrivelse)
            @Html.ValidationMessageFor(model => model.Udgift.Beskrivelse)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Udgift.Dato)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Udgift.Dato)
            @Html.ValidationMessageFor(model => model.Udgift.Dato)
        </div>
        
        @foreach (var beboer in @Model.BeboerChecklist)
        {
            @Html.CheckBox(beboer.Key.Name, beboer.Value);
            @Html.Label(beboer.Key.Name);
            <br />
        }
        
        <p>
            <input type="submit" value="Save" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

TietgenRegnskab/Views/Udgift/Index.cshtml
@model IEnumerable<TietgenRegnskab.Models.Udgift>

@{
    ViewBag.Title = "Index";
}


<h2>Expenses</h2>

@using (Html.BeginForm())
{
    <p>
        Find expenses by payer name: @Html.TextBox("beboerString")  
        <input type="submit" value="Search" />
    </p>
    <p>
        Find expenses by participater name: @Html.TextBox("takerString")  
        <input type="submit" value="Search" />
    </p>
}


<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table>
    <tr>
        <th>
            Afholdt af
        </th>
        <th>
            Beløb
        </th>
        <th>
            Beskrivelse
        </th>
        <th>
            Dato
        </th>
        <th></th>
    </tr>

@foreach (var item in Model.OrderByDescending(m=>m.Dato)) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Beboer.Name)
        </td>
        <td>
            @string.Format("{0:C}", Html.DisplayFor(modelItem => item.Beloeb))
        </td>
        <td>
            @Html.ActionLink(item.Beskrivelse, "Details", "Udgift", new { ID = item.ID }, null)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Dato)
        </td>
        <td>
            @Html.ActionLink("Delete", "Delete", new { id=item.ID })
        </td>
    </tr>
}

</table>